---
title: "Empowering Women's Wellness: Unveiling Smart Device Insights for Bellabeat's Growth and Marketing Strategy"
author: "Prepared by: Mr. Jefferson Mwatati"
date: "`r Sys.Date()`"
output: 
  prettydoc::html_pretty:
    theme: cayman
  html_document:
    toc: true
---


```{r}
#All required packages

#install.packages("tidyverse")
#install.packages("dplyr") #helps in data manipulation
#install.packages("here")  #makes referencing files easy
#install.packages("skimr") #good for summarizing data easily
#install.packages("janitor") #it has functions for cleaning data
#install.packages("prettydoc")

```

```{r}
#Load all installed packages

library(tidyverse)
library(dplyr)
library(lubridate)
library(here)
library(skimr)
library(janitor)
library(knitr)
library(prettydoc)

```



```{r}
# import data
dailyactivity_df <- read_csv("dailyActivity_merged.csv")
```
View first 6 records.

```{r}
#view data
head(dailyactivity_df)
```


```{r}
#import data
sleepday_df <- read_csv("sleepDay_merged.csv")
```




```{r}
#view data
head(sleepday_df)
```




```{r}
#import data
weightloginfo_df <- read_csv("weightLogInfo_merged.csv")
```



```{r}
#view data
head(weightloginfo_df)
``` 

```{r}
#View column names and datatypes 
glimpse(dailyactivity_df)
```

```{r}
# create new column
newdailyactivity_df <- dailyactivity_df %>%
  mutate(newActivityDate = mdy(ActivityDate))
```


```{r}
#select and arrange columns
cleandailyactivity_df <- select(newdailyactivity_df,Id, newActivityDate,TotalSteps,TotalDistance,Calories)
```

```{r}
#view data set
head(cleandailyactivity_df)
```


```{r}
# Calculate statistics
activity_totalrecords <- nrow(cleandailyactivity_df)
activity_totaldays <- length(unique(cleandailyactivity_df$newActivityDate))
activity_totalparticipants <- length(unique(cleandailyactivity_df$Id))
average_daily_steps <- mean(cleandailyactivity_df$TotalSteps)
average_daily_distance <- mean(cleandailyactivity_df$TotalDistance)
average_daily_calories_burned <- mean(cleandailyactivity_df$Calories)

# Print the calculated statistics
cat("Total Activity Records:", activity_totalrecords, "\n")
cat("Total Activity Days:", activity_totaldays, "\n")
cat("Total women participants:", activity_totalparticipants, "\n")
cat("Average of daily steps made:", average_daily_steps, "\n")
cat("Average of daily distance covered:", average_daily_distance, "\n")
cat("Average of daily calories burned:", average_daily_calories_burned, "\n")
```



```{r}
# Determine activity first day and last day
activitydaterange_df <- cleandailyactivity_df %>%
  summarize(
    activity_firstday = min(newActivityDate),
    activity_lastday = max(newActivityDate)
  )

# Display results
head(activitydaterange_df)
```


```{r}
# Calculate the trend in total steps over time
total_steps_by_date <- cleandailyactivity_df %>%
  group_by(newActivityDate) %>%
  summarise(total_steps = sum(TotalSteps))

total_steps_by_date
```


```{r}
# Calculate the trend in total distance over time
total_distance_by_date <- cleandailyactivity_df %>%
  group_by(newActivityDate) %>%
  summarise(total_distance = sum(TotalDistance))
total_distance_by_date
```


```{r}
# Calculate the trend in calories burned over time
calories_burned_by_date <- cleandailyactivity_df %>%
  group_by(newActivityDate) %>%
  summarise(calories_burned = sum(Calories))

calories_burned_by_date
```


```{r}
#Filtering a dataset using the pipe operator to extract specific records
fitnesswoman_001 <- cleandailyactivity_df %>%
  filter(Id=="4020332650") 
```




```{r}
#Filtering a dataset using the pipe operator to extract specific records
fitnesswoman_002 <- cleandailyactivity_df %>%
  filter(Id=="4388161847") 
```






```{r}
#Filtering a dataset using the pipe operator to extract specific records
fitnesswoman_003 <- cleandailyactivity_df %>%
  filter(Id=="2347167796") 
```




```{r}
#Filtering a dataset using the pipe operator to extract specific records
fitnesswoman_005 <- cleandailyactivity_df %>%
  filter(Id %in% c(1503960366, 1624580081, 1844505072, 1927972279, 2022484408, 2026352035, 2320127002, 2347167796, 2873212765, 3372868164, 3977333714, 4020332650))

```






```{r}
glimpse(sleepday_df)
```



```{r}
# Convert the "SleepDay" column to a proper date-time format
sleepday_df$SleepDay <- as.POSIXct(sleepday_df$SleepDay, format = "%m/%d/%Y %I:%M:%S %p")

# Extract the date and time from the converted date-time column
sleepday_df$Date <- as.Date(sleepday_df$SleepDay)
sleepday_df$Time <- format(sleepday_df$SleepDay, "%H:%M:%S")

```


```{r}
#select and arrange columns
cleansleepday_df <- select(sleepday_df,Id,Date,Time,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed)
```


```{r}
#view data
head(cleansleepday_df)
```


```{r}
# Calculate statistics
sleep_totalrecords <- nrow(cleansleepday_df)
sleep_totaldays <- length(unique(cleansleepday_df$Date))
sleep_totalwomen_participants <- length(unique(cleansleepday_df$Id))
minimum_totalminutesasleep <- min(cleansleepday_df$TotalMinutesAsleep)
maximum_totalminutesasleep <- max(cleansleepday_df$TotalMinutesAsleep)
average_totalminutesasleep <- mean(cleansleepday_df$TotalMinutesAsleep)
minimum_TotalTimeInBed <- min(cleansleepday_df$TotalTimeInBed)
maximum_TotalTimeInBed <- max(cleansleepday_df$TotalTimeInBed)
average_TotalTimeInBed <- mean(cleansleepday_df$TotalTimeInBed)

# Print the calculated statistics
cat("Total sleep records:", sleep_totalrecords, "\n")
cat("Total sleep days recorded:", sleep_totaldays, "\n")
cat("Total women participants in sleep records:", sleep_totalwomen_participants, "\n")
cat("Minimum minutes asleep :", minimum_totalminutesasleep, "\n")
cat("Maximum minutes asleep:", maximum_totalminutesasleep, "\n")
cat("Average minutes asleep:", average_totalminutesasleep, "\n")
cat("Minimum time in bed:", minimum_TotalTimeInBed, "\n")
cat("Maximum time in bed:", maximum_TotalTimeInBed, "\n")
cat("Average time in bed:", average_TotalTimeInBed, "\n")
```



```{r}
# Calculate the correlation coefficient between total minutes asleep and total time in bed
cor(cleansleepday_df$TotalMinutesAsleep, cleansleepday_df$TotalTimeInBed)
```



```{r}
# Check the correlation between numerical variables
cor(cleansleepday_df[, c("TotalSleepRecords", "TotalMinutesAsleep", "TotalTimeInBed")])

```


```{r}
# Calculate the trend in total minutes asleep over time
TotalMinutesAsleep_by_date <- cleansleepday_df %>%
  group_by(Date) %>%
  summarise(total_minutes_asleep = sum(TotalMinutesAsleep))

TotalMinutesAsleep_by_date
```




```{r}
# Calculate the trend in total time in bed over time
TotalTimeInBed_by_date <- cleansleepday_df %>%
  group_by(Date) %>%
  summarise(total_time_in_bed = sum(TotalTimeInBed))

TotalTimeInBed_by_date
```


```{r}
#Filter specific records
fitnesswomenTTIB <- cleansleepday_df %>%
  filter(Id %in% c(8378563200))

```




```{r}
glimpse(weightloginfo_df)
```




```{r}
#Change the date column datatype from chr to datetime
weightloginfo_df$Date <- as.POSIXct(weightloginfo_df$Date, format = "%m/%d/%Y %I:%M:%S %p")

#Create a column for date only
weightloginfo_df$DateOnly <- as.Date(weightloginfo_df$Date)

#Create a column for Time only
weightloginfo_df$TimeOnly <- format(weightloginfo_df$Date, format = "%H:%M:%S")


```



```{r}
#select and arrange columns
cleanweightloginfo_df <- select(weightloginfo_df,Id,DateOnly,TimeOnly,WeightKg,WeightPounds,BMI,IsManualReport,LogId)
```




```{r}
#View data
head(cleanweightloginfo_df)
```




```{r}
# Calculate statistics
weightinfo_totalrecords <- nrow(cleanweightloginfo_df)
weightinfo_totaldays <- length(unique(cleanweightloginfo_df$DateOnly))
weightinfo_totalparticipants <- length(unique(cleanweightloginfo_df$Id))
mean_weight <- mean(cleanweightloginfo_df$WeightKg)
min_weight <- min(cleanweightloginfo_df$WeightKg)
max_weight <- max(cleanweightloginfo_df$WeightKg)


# Print the calculated statistics
cat("Total Weightinfo Records:", weightinfo_totalrecords, "\n")
cat("Total Weightinfo collection Days:", weightinfo_totaldays, "\n")
cat("Total women participants:", weightinfo_totalparticipants, "\n")
cat("Average Weight:", mean_weight, "\n")
cat("Minimum Weight:", min_weight, "\n")
cat("Maximum Weight:", max_weight, "\n")

```



```{r}
correlation <- cor(cleanweightloginfo_df$WeightKg, cleanweightloginfo_df$BMI)
cat("Correlation between Weight and BMI:", correlation, "\n")

```




```{r}
# Group the data and calculate the counts
grouped_IsManualReport <- cleanweightloginfo_df %>%
  group_by(IsManualReport) %>%
  summarize(no_of_reports = n())

grouped_IsManualReport
```


```{r}
# Create a new column with the BMI categories
BMI_category_Count <- cleanweightloginfo_df %>%
  mutate(BMI_Category = case_when(
    BMI < 18.5 ~ "Underweight",
    BMI >= 18.5 & BMI < 25 ~ "Normal weight",
    BMI >= 25 & BMI < 30 ~ "Overweight",
    BMI >= 30 & BMI < 35 ~ "Obesity",
    BMI >= 35 & BMI < 40 ~ "Class I Obesity",
    BMI >= 40 & BMI < 45 ~ "Class II Obesity",
    BMI >= 45 ~ "Class III Obesity"
  ))

# Count the occurrences of each BMI category
counted_categories <- BMI_category_Count %>%
  group_by(BMI_Category) %>%
  summarise(Count = n())

counted_categories

```




```{r}
# Plot the trend in total steps over time
activity_firstday <- min(cleandailyactivity_df$newActivityDate)
activity_lastday <- max(cleandailyactivity_df$newActivityDate)

ggplot(total_steps_by_date, aes(newActivityDate, total_steps)) +
  geom_line(color = "darkblue", linewidth = 1.2) +
  labs(title = "Tracking Progress: Total Steps Trend Over Time",
       subtitle=paste0("Analyzing Activity Data from: ", activity_firstday, " to ", activity_lastday),
       caption=paste0("Prepared by Mr. Jefferson Mwatati"),
       x="Activity Date",
       y="Total Steps")

```



```{r}
# Plot the trend in total distance over time
ggplot(total_distance_by_date, aes(newActivityDate, total_distance)) +
  geom_line(color = "darkgreen", linewidth = 1.2) +
  labs(title = "Total Distance Trend Analysis",
       subtitle=paste0("Exploring Changes in Total Distance Covered from: ", activity_firstday, " to ", activity_lastday),
       caption=paste0("Prepared by Mr. Jefferson Mwatati"),
       x="Activity Date",
       y="Total Distance")

```



```{r}
# Plot the trend in calories burned over time
ggplot(calories_burned_by_date, aes(newActivityDate, calories_burned)) +
  geom_line(color = "purple", linewidth = 1.2) +
  labs(title = "Tracking Energy Expenditure: Trend in Calories Burned Over Time",
       subtitle=paste0("Analyzing Activity Data from: ", activity_firstday, " to ", activity_lastday),
       caption=paste0("Prepared by Mr. Jefferson Mwatati"),
       x="Activity Date",
       y="Calories Burned")
```



```{r}
ggplot(fitnesswoman_001, aes(newActivityDate, TotalSteps)) +
  geom_line(color = "darkblue", linewidth = 1.2) +
  labs(title = "Tracking Total Steps: Unveiling the 31-Day Journey",
       subtitle=paste0("A Comprehensive Trend Analysis of Participant's Activity"),
       caption=paste0("Prepared by Mr. Jefferson Mwatati"),
       x="Activity Date",
       y="Total Steps")
```





```{r}
ggplot(fitnesswoman_002, aes(newActivityDate, TotalSteps)) +
  geom_line(color = "darkblue", linewidth = 1.2) +
  labs(title = "Exploring Activity Fluctuations: A 31-Day Step Journey",
       subtitle=paste0("Analyzing Variations in Total Steps for a Month"),
       caption=paste0("Prepared by Mr. Jefferson Mwatati"),
       x="Activity Date",
       y="Total Steps")
```



```{r}
ggplot(fitnesswoman_003, aes(newActivityDate, TotalSteps)) +
  geom_line(color = "darkblue", linewidth = 1.2) +
  labs(title = "Monthly Total Steps Analysis: Unveiling Activity Trends",
       subtitle=paste0("Exploring 31 Days of Physical Activity Patterns"),
       caption=paste0("Prepared by Mr. Jefferson Mwatati"),
       x="Activity Date",
       y="Total Steps")
```   



```{r}
ggplot(fitnesswoman_005, aes(newActivityDate, TotalSteps)) +
  geom_line(color = "darkblue", linewidth = 1.2) +
  facet_wrap(~Id) +
  labs(title = "Individual Total Steps Analysis: A Multifaceted View",
       subtitle=paste0("Exploring 31 Days of Activity Trends for Different Women"),
       caption=paste0("Prepared by Mr. Jefferson Mwatati"),
       x="Activity Date",
       y="Total Steps")
```



```{r}
# Plot the trend in total minutes asleep over time

ggplot(TotalMinutesAsleep_by_date, aes(Date, total_minutes_asleep)) +
  geom_line(color = "darkblue", linewidth = 1.2) +
  labs(title = "Exploring Sleep Patterns: Total Minutes Asleep Over Time",
       subtitle=paste0("Analyzing Sleep Trends Across Dates for 24 Women"),
       caption=paste0("Prepared by Mr. Jefferson Mwatati"),
       x="Date",
       y="Total Minutes Asleep")

```



```{r}
# Plot the trend in total time in bed over time

ggplot(TotalTimeInBed_by_date, aes(Date, total_time_in_bed)) +
  geom_line(color = "darkred", linewidth = 1.2) +
  labs(title = "Tracking Bedtime Trends: Total Time in Bed Over a Month",
       subtitle=paste0("Analyzing Bedtime Duration Patterns Across Dates for 24 Women"),
       caption=paste0("Prepared by Mr. Jefferson Mwatati"),
       x="Date",
       y="Total Time in Bed")

```



```{r}
ggplot(fitnesswomenTTIB, aes(Date,TotalTimeInBed)) +
  geom_line(color = "maroon", linewidth = 1.2) +
  labs(title = "Exploring Bedtime Patterns: 31-Day Total Time in Bed Analysis",
       subtitle=paste0("Tracing a Participant's Bedtime Trends Over Time"),
       caption=paste0("Prepared by Mr. Jefferson Mwatati"),
       x="Date",
       y="Total Time in Bed")+
  theme_light()

```




```{r}
# Create a histogram to visualize the distribution of TotalMinutesAsleep

ggplot(cleansleepday_df, aes(x = TotalMinutesAsleep)) +
  geom_histogram(binwidth = 30, col = "white", fill = "darkred") +
  labs(title = "Understanding Sleep Duration Distribution",subtitle=paste0("Exploring the Spread of Total Minutes Asleep in a Dataset"),x = "Minutes Asleep", y = "Frequency", caption=paste0("Prepared by Mr. Jefferson Mwatati")) +
  theme_bw()

```



```{r}
# Plot the distribution of total time in bed
ggplot(cleansleepday_df, aes(x = TotalTimeInBed)) +
  geom_histogram(binwidth = 10, col = "white", fill = "darkblue") +
  labs(title = "Exploring Bedtime Duration Distribution",subtitle=paste0("Analyzing the Spread of Total Time in Bed within the Dataset"), x = "Total Time in Bed (minutes)", y = "Count", caption=paste0("Prepared by Mr. Jefferson Mwatati")) +
  theme_light()
```


```{r}
# Create a scatter plot with regression line
ggplot(cleansleepday_df, aes(x = TotalMinutesAsleep, y = TotalTimeInBed)) +
  geom_point(color = "brown") +
  geom_smooth(method = "lm", se = FALSE,linewidth = 1.4, color = "green") +
  labs(x = "Total Minutes Asleep", y = "Total Time in Bed (minutes)", title = "Exploring the Relationship between Sleep Duration and Bedtime",subtitle=paste0("A strong positive correlation exists between total minutes asleep and total time in bed"), caption=paste0("Prepared by Mr. Jefferson Mwatati"))+
   theme_light()
  

```


```{r}
ggplot(cleanweightloginfo_df, aes(x = WeightKg)) +
  geom_histogram(binwidth = 9, fill = "blue", color = "black") +
  labs(x = "Weight (Kg)", 
       y = "Frequency", 
       title = "Distribution of Weight in Kilograms",
       subtitle=paste0("Frequency Distribution of Recorded Weights"),
       caption=paste0("Prepared by Mr. Jefferson Mwatati"))

```


```{r}
# Create a pie chart with percentages
ggplot(grouped_IsManualReport, aes(x = "", y = no_of_reports, fill = factor(IsManualReport))) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  labs(fill = "IsManualReport",
       title = "Manual and Automatic Reports",
       subtitle=paste0("Proportion of Reports Generated Manually and Automatically"),
       caption=paste0("Prepared by Mr. Jefferson Mwatati")) +
  scale_fill_manual(values = c("TRUE" = "purple", "FALSE" = "orange")) +
  geom_text(aes(label = scales::percent(no_of_reports / sum(no_of_reports))), 
            position = position_stack(vjust = 0.5)) +
  theme_void()


```
 

```{r}
# Create a pie chart
ggplot(counted_categories, aes(x = "", y = Count, fill = BMI_Category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  labs(fill = "BMI Category",
       title = "BMI Category Distribution",
       subtitle=paste0("Proportion of Different BMI Categories Among Individuals"),
       caption = "Prepared by Mr. Jefferson Mwatati") +
  scale_fill_brewer(palette = "Set1") +  
  geom_text(aes(label = scales::percent(Count / sum(Count))), 
            position = position_stack(vjust = 0.5)) +
  theme_void()
```






